### ISSUE TITLE
Conditional episode only partially restores state

### ISSUE THREAD

**Issue by edbennett** [swcarpentry/python-novice-inflammation#1051]
[Episode 7](https://swcarpentry.github.io/python-novice-inflammation/instructor/07-cond.html) includes the text

> Therefore, if you’re working in a new Python session, make sure to load the module with:
>
> ```import numpy```

But the subsequent code block then refers to `data`, which will not be defined if the learner (or instructor) is in a new Python session.

I'd suggest that either this section should re-load the `data`, or the quoted section should be removed, for consistency. (My personal preference would be the former.)

**Comment by AlbertoImg** [comment]
Hi @edbennett, thanks for your contribution. The suggestion is now in the last version. Thanks again!
