### ISSUE TITLE
Adding in a little extra info about polynomials

### ISSUE THREAD

**Issue by wood-chris** [swcarpentry/python-novice-inflammation#1077]
### How could the content be improved?

For those who are unfamiliar (or have only briefly touched) polynomials before, I wonder if a little more explanation would be useful, e.g. modifying the paragraph to say 

Suppose you have encoded a polynomial as a list of coefficients in the following way: the first element is the constant term, the second element is the coefficient of the linear term, the third is the coefficient of the quadratic term, etc, where the polynomial is of the form

ax^0 + bx^1 + cx^2

(when writing polynomials mathematically, the x^0 is often omitted since this equals 1)

(the equation could be LaTeX-ified, if the renderer supports that)

### Which part of the content does your suggestion apply to?

https://swcarpentry.github.io/python-novice-inflammation/05-loop.html#computing-the-value-of-a-polynomial

**Comment by AlbertoImg** [comment]
Hello @wood-chris, thank you for your valuable feedback. We will keep it in mind for future developments, but for now the point would not be included to keep the focus of the exercise on the programming side. Thank you for the suggestion.

**Comment by wood-chris** [comment]
Hi @AlbertoImg - thanks for the reply! I made the suggestion because I've taught many instances of this course where the attendees were unable to complete the challenge because they didn't understand the maths :) (and only after I explained the definition of polynomial could the do the programming side of the exercise)

**Comment by AlbertoImg** [comment]
Hi @wood-chris. Yes you are right, now we are going considering this contribution and how to add it. Will keep you posted. Thanks again
