### ISSUE TITLE
Issues at 03-loop.md

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/python-novice-inflammation#13]
Fromhttps://github.com/swcarpentry/lesson-template/blob/gh-pages/tools/check.py:

- [ ] Document contains heading not specified in the template: For Loops
- [ ] Document contains heading not specified in the template: Lists
- [ ] Document contains heading not specified in the template: Processing Multiple Files
- [ ] The topic page should not have sub-headings outside of special blocks. If a topic needs sub-headings, it should be broken into multiple topics.

**Comment by janetriley** [comment]
Please see my pull request at https://github.com/swcarpentry/python-novice-inflammation/pull/50 .

**Comment by janetriley** [comment]
@r-gaia-cs, my pull request was merged. This ticket may be closed.

**Comment by r-gaia-cs** [comment]
@janetriley Thanks for the pull request and sorry for not followed it.
