### ISSUE TITLE
imports in the python lesson

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/python-novice-inflammation#133]
The first lesson for the python lesson [1] shows importing `numpy` and `matplotlib.pyplot` without an alias.  but in the next lesson where we go back to plotting inflammation data [2]
we import `glob` but the code in the for loop use `np` and `plt` aliases.

If students follow the current lesson material, they would not know to import using an alias and will trip up when the code fails

[1] http://swcarpentry.github.io/python-novice-inflammation/01-numpy.html
[2] http://swcarpentry.github.io/python-novice-inflammation/04-files.html

**Comment by gvwilson** [comment]
@chendaniely is this still an issue?

**Comment by valentina-s** [comment]
This has been fixed. Thanks!
