### ISSUE TITLE
I was confused by the official location of the HTML of the lessons

### ISSUE THREAD

**Issue by rdhyee** [swcarpentry/python-novice-inflammation#138]
In preparing for a [workshop](http://cdips.physics.berkeley.edu/2015-cdips-data-science-workshop/) in which I will point to this material, I was working through the lessons at https://swcarpentry.github.io/python-novice-inflammation/01-numpy.html.  I ran into problems, which I started to annotate using hypothes.is (e.g., https://via.hypothes.is/https://swcarpentry.github.io/python-novice-inflammation/01-numpy.html).

This morning, I then encountered http://www.software-carpentry.org/v5/novice/python/01-numpy.html, which seems to have been a differe (and perhaps more correct) version of https://swcarpentry.github.io/python-novice-inflammation/01-numpy.html.

Please make clearer the different versions of the material on the web.

**Comment by r-gaia-cs** [comment]
> https://swcarpentry.github.io/python-novice-inflammation/01-numpy.html

is the bleeding edge version of our lessons.
Changes on it can happen any time.

> http://www.software-carpentry.org/v5/novice/python/01-numpy.html

This is the frozen version of our lessons.
As fas as I remember,
it is the version before we split the `bc` repository.

> Please make clearer the different versions of the material on the web.

If you go to http://software-carpentry.org/lessons.html
you will not find any link to `http://www.software-carpentry.org/v5/*`.
We only keep the pages active to avoid links at others places to stop working.
