### ISSUE TITLE
What is the inflammation data?

### ISSUE THREAD

**Issue by karinlag** [swcarpentry/python-novice-inflammation#179]
Just wondering what the data is a measurement of. It is certainly not temperature, is it CRP count or something else? 

Knowing what it is, and the scale of the measurement, would make it easier to teach.

**Comment by gvwilson** [comment]
It's completely synthetic - we need to replace it with something that 
has a real story behind it (which I'm hoping to do in December once 
instructor training is out of the way).

**Comment by karinlag** [comment]
On 01.12.2015 11:00, Greg Wilson wrote:
> It's completely synthetic - we need to replace it with something that
> has a real story behind it (which I'm hoping to do in December once
> instructor training is out of the way).

I know that, but isn't it supposed to be a fake "something" at least? 
Why else call it inflammation, and not something else, like, I dunno, 
cloud coverage?

karin

**Comment by iglpdc** [comment]
You could say is the cell count of white blood cells in some units over some baseline (so it's always positive and grows) before applying an antibiotic treatment in patients with some sort of bacterial infection, but I'm not a (real) doctor :)

**Comment by karinlag** [comment]
Thanks! That makes it easier to teach :)

**Comment by maneesha** [comment]
Any progress on this?  I was about to post an issue with the exact same question since I'm teaching it in a couple of weeks.  For now I'm planning on presenting it as fake data, just to be able to look at trends, etc.

**Comment by gvwilson** [comment]
It *is* fake data, and that's part of the story: something very similar 
was presented along with a paper I was given to review several years 
ago, and it when I plotted maxima and minima, it became clear that it 
wasn't real.
