### ISSUE TITLE
Figure numbering for figure captions

### ISSUE THREAD

**Issue by zmughal** [swcarpentry/python-novice-inflammation#20]
Since Pandoc can generate figure captions for images, it would be nice to be able to use figure numbering to refer to figures from the text (Figure 1, Figure 2, etc.). Currently, the figure captions are escaped by using the `<backslash><white-space>` syntax.

This is currently not possible directly in Pandoc, but there are some [solutions discussed](https://github.com/swcarpentry/python-novice-inflammation/pull/7#discussion_r23197234) by @r-gaia-cs that involve CSS or Pandoc filters.

**Comment by gvwilson** [comment]
Has this one been filed on 
https://github.com/swcarpentry/lesson-template ?  If not, could you please ?

**Comment by r-gaia-cs** [comment]
@zmughal Thanks for filed this issue and the one at https://github.com/swcarpentry/lesson-template. Are you OK to close this one to keep the conversation on https://github.com/swcarpentry/lesson-template/issues/138?

**Comment by zmughal** [comment]
Yeah, I'll close it.
