### ISSUE TITLE
Optional callouts

### ISSUE THREAD

**Issue by tbekolay** [swcarpentry/python-novice-inflammation#210]
Many of our callouts add additional information to the lesson (and are great for people reading through the lessons) but may not be necessary to teach during workshops. It could be useful to note that the callouts aren't necessarily things that need to be taught in a workshop, but are primarily there for interest or for further reading. A few ways we could do this (no real preference toward one; comments with preferences welcome!)

1. Add a note to the instructor guide specifying that callouts don't need to be taught unless it seems useful.
2. Add a callout on the index page explaining what callouts are used for (I think these appear at the start of many technical books like the "for Dummies" series).
3. Make all callout boxes collapsed by default, but shown when an arrow is clicked (as in, e.g., [Bootsrap collapse](http://www.w3schools.com/bootstrap/bootstrap_collapse.asp))
4. Make a separate "optional" callout that is collapsed by default, but shown when an arrow is clicked.
5. Make a separate "optional" callout that is rendered differently than the usual blue callout.

**Comment by gvwilson** [comment]
Relocated to https://github.com/swcarpentry/lesson-template/issues/289
