### ISSUE TITLE
If/else and chapter order

### ISSUE THREAD

**Issue by GoreGrindGeek** [swcarpentry/python-novice-inflammation#263]
"Ternary" if/else is not mentioned in the lessons. A good guide can be found here:
http://stackoverflow.com/questions/394809/does-python-have-a-ternary-conditional-operator

Another suggestion would be to reverse chapter order. Tutorials start with plots and charts and then digress into shorthand operators and if/else statements. I personally would've started with the latter two, then move onto strings and "lists" and do charts at the very end.

I hope this helps. Sincerely, one of the guys who've attended the course.

**Comment by jangari** [comment]
I agree. I think starting with the matplotlib stuff is too high a bar for most people when they're absolutely new to python. I would also suggest doing the basics, which are mainly covered in conditionals, loops, etc., first, and then on the morning of the second day, bring in the dataset to analyse. This also has the benefit of bridging from loops in the Unix Shell novice course.

**Comment by tbekolay** [comment]
Hey! Thanks for your feedback. The original intention was to start by motivating the somewhat tedious introductory material by saying "hey, look at what you can do with just a few lines of Python. Okay, now that you're hooked, here's how it all works." But I think you're both right that in most cases, the motivation exists coming into the workshop and/or the initial Matplotlib stuff is too intimidating. Greg Wilson has been working on a new novice lesson, [python-novice-gapminder](https://swcarpentry.github.io/python-novice-gapminder/) to resolve these and other similar issues. Take a look at the lesson there, does that organization make more sense?

**Comment by GoreGrindGeek** [comment]
Thank you.

In the "Novice Gapminder" I'd suggest moving "The Call Stack" to in between "Built-in Functions and Help" and "Error Messages", and "For Loops" should probably come before "Lists", because a list is a fairly complex data structure compared to a loop.
