### ISSUE TITLE
overlap in figure: Operation Across Axes

### ISSUE THREAD

**Issue by medelero** [swcarpentry/python-novice-inflammation#270]
There is an overlapping in the figure "Operation Across Axes" of the section 01-Numpy.

**Comment by btel** [comment]
That's what it looks like in Firefox 46 on Linux:

![operations_across_axes](https://cloud.githubusercontent.com/assets/41565/16021278/052bb3b4-31b2-11e6-9d28-936a0b5c250b.png)

See also #271
