### ISSUE TITLE
overlap in first figure 05-cond

### ISSUE THREAD

**Issue by medelero** [swcarpentry/python-novice-inflammation#271]
overlap in first figure of the 05-cond Conditionals.

**Comment by btel** [comment]
That's what it looks like in Firefox 46 on Linux:


![conditionals](https://cloud.githubusercontent.com/assets/41565/16021301/2e6e50a6-31b2-11e6-81e6-cd00a7a19561.png)


see also #270

**Comment by gvwilson** [comment]
Is this still an issue?

**Comment by valentina-s** [comment]
This has been resolved by replacing with .png's.
