### ISSUE TITLE
Introduce enumerate function

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/python-novice-inflammation#276]
#193 introduced `enumerate`, which is very useful and ought to be included in exercises, but which needs a better motivating example.

**Comment by dstndstn** [comment]
it looks like this issue was addressed in PR #323 which has been merged -- so this issue should be closed.

**Comment by FelixLiu-SF** [comment]
I think the current enumerate explanation in Computing the Value of a Polynomial can be improved by explaining all of the variables - not just i and x. 

Underneath the example,
for i, x in enumerate(xs):
    # Do something with i and x

It currently reads: "The loop above assigns the index to i and the value to x." 
It may be better to say something like: "The code above loops through xs, assigning the index to i and the value to x."

**Comment by valentina-s** [comment]
Thanks for the suggestion. Would you like to submit a PR to add this modification?
