### ISSUE TITLE
Add Pandas introductory session

### ISSUE THREAD

**Issue by snamburi3** [swcarpentry/python-novice-inflammation#291]
Pandas is one of the most commonly used Python modules. I think we need to add a Pandas introductory lesson covering at least the basics. 
- dataframes, series
- pandas objects
- loading and exporting data
- selecting and looking up the data
- simple operations and stats
- Working with time-series data

**Comment by gvwilson** [comment]
I agree that Pandas is important - what would you take out of the 
existing lesson to make room for the new material?  (We already struggle 
to get through this in a full day.)  Alternatively, you may want to join 
the discussion on 
https://github.com/swcarpentry/python-novice-gapminder/issues/70.

**Comment by snamburi3** [comment]
Thanks, @gvwilson. Yes, we already have a Intro to Pandas in [python-novice-gapminder](http://swcarpentry.github.io/python-novice-gapminder/11-data-frames/) . Closing this issue.
