### ISSUE TITLE
ids not set in the glossary

### ISSUE THREAD

**Issue by tbekolay** [swcarpentry/python-novice-inflammation#305]
Before, we could link to specific elements in the glossary with anchor links (e.g. `[word](/references/#word)`). However, these no longer work because the definition list in the glossary does not have `id` attributes set (which is how the anchor links work).

Is this something we should fix here or in the template @gvwilson?

**Comment by gvwilson** [comment]
The next release of Kramdown will automatically generate IDs for 
definition list items.

**Comment by tbekolay** [comment]
Even better!
