### ISSUE TITLE
Set up Travis to validate the exercises in pull requests

### ISSUE THREAD

**Issue by astrofrog** [swcarpentry/python-novice-inflammation#319]
It would be easy to set up Travis to validate all the notes, running e.g. `make lesson-check-all`, to make sure that the notes always remain valid. In future, one could even set it up so that examples can be run and the output checked (to make sure the examples are up-to-date and functional). If an admin of the repository can enable Travis, I'd be happy to open a PR to add the required configuration.

**Comment by petebachant** [comment]
Travis could be beneficial for all lesson PRs, so you may want to create an issue/PR against one of the template or style repos. cc @gvwilson

**Comment by astrofrog** [comment]
@petebachant would it make sense to maybe try in this one as an example first, since it may take a bit of fiddling the first time, and it would be easiest to test out on a real life case rather than a template? Then once it works, we could open a PR to the template or style repos?

**Comment by vahtras** [comment]
Travis is set up for the SciPy lecture notes so that all code snippets are
executed and there output tested with nose+doctest. If that is something we
would like to have one can look there for inspiration:
https://github.com/scipy-lectures/scipy-lecture-notes

Regards,
Olav

**Comment by maxim-belkin** [comment]
Closing this as Travis-CI was added to this repo.
