### ISSUE TITLE
Python 3 floating point rounding

### ISSUE THREAD

**Issue by hpourreza** [swcarpentry/python-novice-inflammation#328]
When I run `2.2*55` in Python 3, I get `121.00000000000001` instead of `121.0` that is on the course website (01_numpy). I think the output on the course website is from Python 2 that prints `121.0`.

**Comment by rgaiacs** [comment]
@hpourreza Thanks for the issue. Could you send a pull request to fix it?

**Comment by neon-ninja** [comment]
On my machine, I get the same result in python2 and python3. I think the difference occurs depending on whether you're running a 32-bit or 64-bit version of python - see https://docs.python.org/3/tutorial/floatingpoint.html

python 2.7.10 on ideone: http://ideone.com/WYcuze = 121.0
python 2.7.10 on repl.it: https://repl.it/F26E/0 = 121.00000000000001
python 3.4 on ideone: http://ideone.com/DCQgI6 = 121.00000000000001
