### ISSUE TITLE
Mentioning recursion in lesson on Creating Functions label:instructor-training

### ISSUE THREAD

**Issue by samedling** [swcarpentry/python-novice-inflammation#357]
In lesson 6, on Creating Functions, I think that we should at least have an exercise demonstrating recursion.  If there isn't always time to mention it in the main lesson, that's ok, but it should be available to learners seeking to work through the exercises to understand the full utility of functions.

**Comment by sgenie68** [comment]
I can take it up for fixing.

**Comment by tbekolay** [comment]
I think that recursion is well outside of the scope of this lesson.

The purpose of the lesson is to get scientists up and running with some basic Python programming, not to have them appreciate the full utility of functions and other abstractions used in computer science. I know that in functional programming languages, recursion is a central concept necessary to be productive; however, in my 7-ish years of doing scientific computing with Python, I've never had an absolute need to use recursion. Yes, you can come up with specific examples where it results in more aesthetically pleasing or efficient code, but for the scientist who just wants to advance from spreadsheets to programming, recursion is more likely to intimidate than empower.

@valentina-s, do you agree with my thoughts here?

**Comment by sgenie68** [comment]
Thanks, Trevor, however I disagree, - recursion is not only valuable tool in many cases, but it is also a demonstration of a feature which is not apparent initially. There is no need to go deep and explain the intricacies of stack handling and suchlike, but having a paragraph or two would, in my opinion, be beneficial.

**Comment by tbekolay** [comment]
> having a paragraph or two would, in my opinion, be beneficial.

I appreciate that recursion can be a useful tool in some cases. However, there are so many useful tools in programming, Python programming, the data science stack in Python, and so on that we have to be frugal in what concepts we include in a lesson which is, frankly, already too long.

The rule of thumb we've used in the past is that we can only include new concepts if we take out a concept that's currently in the lesson and that imposes a comparable cognitive load. Do you have suggestions of what we would remove to make room for recursion?

**Comment by valentina-s** [comment]
I agree that recursion is not on the top list of things to be taught to a scientific programmer. I am not sure I remember the last time I have used a recursion. Also, from personal experience teaching it, it is not a very easy concept, so briefly mentioning it might confuse them differentiating from loops. Hopefully, they will continue programming and will encounter the concept sooner or later.
