### ISSUE TITLE
Location of code and data does not agree with lesson 06-cmdline

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/python-novice-inflammation#4]
The code and the data used in the lesson 06-cmdline have been moved to separate subdirectories. Thus the code as written in the lesson would not be executable. Is your plan to have this layout for the repo only, and then in live workshops have everything in one directory?

I ask because I know that novices struggle with navigating directories (most will have just seen it for the first time in the shell lesson). For the [novice R lessons][r], we are trying to keep the source executable in R Markdown files. For this to work, what is written in the lesson has to correspond to the actual layout in the lesson repository. We recently moved the inflammation files to a subdirectory and updated the lessons. However, we have not yet moved the scripts. I hesitate to do so because this lesson is already challenging, and it is inevitable that many students will save the R script in the current working directory because they did not `cd code` before running `nano`.

I'd appreciate any advice on how to proceed.

[r]: https://github.com/swcarpentry/r-novice-inflammation

**Comment by abostroem** [comment]
@gvwilson I think this one is for you...

**Comment by jdblischak** [comment]
Reading through the lesson template guide, I found my issue addressed in the section [Code, Data, and Figures][code]:

1.  This mirrors the layout a scientist would use for actual work.
    However, it may cause novice learners problems.  If a program is
    in `code/a.py`, and contains a reference to a data file
    `../data/b.csv`, then if the user runs the program from the root
    directory using `python code/a.py`, it will be unable to find the
    data file (since the program's working directory will be the root
    directory, not the `data` directory).

However, it only acknowledges the problem, but provides no guidance on how it could be solved. I don't have any hard numbers, but it is my understanding that the majority of our workshops these days are for novice learners (please correct me if I am wrong). Should we not optimize our novice lessons for use in novice workshops?

[code]: https://github.com/swcarpentry/lesson-template/blob/gh-pages/LAYOUT.md#code-data-and-figures

**Comment by gvwilson** [comment]
We should optimize for novices - what do you believe the correct 
solution for them is?

**Comment by jdblischak** [comment]
I'm not sure what the best solution is. But after reading the comments on the [blog post][post], it seems that a lot of the concern was making the template suitable for those that develop the lessons. While I also personally like the layout, I know that getting a room full of novices to `cd` back and forth while writing scripts is very difficult. For now, I'd like to try a compromise approach: put the data files in their own subdirectory, but keep the code examples in the base directory along with the topic pages.

[post]: http://software-carpentry.org/blog/2014/10/new-lesson-template-v2.html

**Comment by zmughal** [comment]
I only just came across this a week ago, but the [ProjectTemplate](http://projecttemplate.net/) for R seems really nice for both beginners and advanced users. It distills best practices down to just 2 lines:

```r
library('ProjectTemplate')
load.project()
```

I've been contemplating creating something similar for the Perl lesson I'm working on. I would like to remove boilerplate as much as possible. This may be too magical though.

**Comment by gvwilson** [comment]
Too magical to start with, but @jdblischak may have a different opinion 
- John?

**Comment by jdblischak** [comment]
I think using such a template would be going way too fast for novices. Since they have never programmed before, the most natural thing is to start with everything in the same directory. If by the end of a workshop you have managed to teach novices that they should separate their data files into a subdirectory, I would consider that a win. Two days goes really fast.

Also, the goal is to focus as much as possible on language-agnostic principles, and specific libraries and directory structures will not translate well to other programming languages.

**Comment by zmughal** [comment]
OK, I see. Thanks for the advice!

**Comment by jdblischak** [comment]
No problem. Good luck!

**Comment by abostroem** [comment]
We are currently starting with the lessons in the central directory and only asking students to cd in later lessons. Is this a fair compromise between being easy for beginners and well organized for developers (and students future selves?)

**Comment by gvwilson** [comment]
Can this one be closed as stale?

**Comment by jdblischak** [comment]
Yes, it can be closed. Basically for the R lessons, we are not moving the code files to a subdirectory as instructed by the [template](https://github.com/swcarpentry/lesson-example/blob/gh-pages/LAYOUT.md#code-data-and-figures). This is because our lessons are executable, and this would break all the lessons. The [novice Python lesson](https://github.com/swcarpentry/python-novice-inflammation) has moved the code files to a subdirectory, however the lesson on [command line programs](https://swcarpentry.github.io/python-novice-inflammation/10-cmdline.html) does not acknowledge this directory structure (it also does not specify that the data files are in a subdirectory either).

**Comment by gvwilson** [comment]
Hm - OK, I'll close this one and open another about getting the lessons consistent about use of sub-directories - thanks.
