### ISSUE TITLE
Incorrect links to Glossary from in 01-numpy.md

### ISSUE THREAD

**Issue by agbeltran** [swcarpentry/python-novice-inflammation#400]
The links to the glossary are wrong in the 01-numpy.md lesson.

For example, the link to the library definition in the glossary from the lesson file:

https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/_episodes/01-numpy.md

currently points to

http://swcarpentry.github.io/python-novice-inflammation/01-numpy/reference.html#library

which gives a 404.

The correct link is: 

http://swcarpentry.github.io/python-novice-inflammation/reference/#library

**Comment by tbekolay** [comment]
Thanks for pointing this out! I made #403 to address it.
