### ISSUE TITLE
Fix for solution for 'Moving plots around' in 01-numpy

### ISSUE THREAD

**Issue by agbeltran** [swcarpentry/python-novice-inflammation#402]
The solution given loads the data from outside the ```data``` folder, but all the previous scripts assumed that the notebook is run from inside the ```data``` folder.

So, change
```data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')```
to 
```data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')```

**Comment by valentina-s** [comment]
Indeed, the call should be from the data folder. Are you willing to submit a pull request with the fix?

**Comment by agbeltran** [comment]
sure, I will, thanks

**Comment by agbeltran** [comment]
I have just checked and this has already been fixed in 
https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/_episodes/01-numpy.md

Closing the issue.
