### ISSUE TITLE
Unwanted __MACOSX folder in python-novice-inflammation-code.zip

### ISSUE THREAD

**Issue by pllim** [swcarpentry/python-novice-inflammation#404]
I followed instructions at http://swcarpentry.github.io/python-novice-inflammation/setup/ and downloaded `python-novice-inflammation-code.zip` to my Linux machine. Then, I unzipped it as follows:
```
unzip python-novice-inflammation-code.zip
```
Now, I see the following in my working directory:
```
code/
__MACOSX/
python-novice-inflammation-code.zip
```
Here is the content of `__MACOSX`:
```
code/
  ._argv_list.py
  ._arith.py
  ._check.py
  ._count_stdin.py
  ._errors_01.py
  ._errors_02.py
  ._gen_inflammation.py
  ._line_count.py
  ._my_ls.py
  ._readings_01.py
  ._readings_02.py
  ._readings_03.py
  ._readings_04.py
  ._readings_05.py
  ._readings_06.py
  ._readings_07.py
  ._readings_08.py
  ._readings_09.py
  ._rectangle.py
  ._sys_version.py
._code
```
Is there a reason you include this `__MACOSX` folder in your distribution?

**Comment by rgaiacs** [comment]
`__MACOSX` is a hidden folder used by macOS but visible on other OS. Ideally the zip file would be generated by a continuous integration system but we don't have this flexibility with GitHub Pages.

**Comment by valentina-s** [comment]
I think I removed it in this version: https://github.com/swcarpentry/python-novice-inflammation/blob/fix_zipfile/code/python-novice-inflammation-code.zip

Can you double check if it cleaned (I am on Mac so it is invisible to me)?

**Comment by amjames** [comment]
@valentina-s the `__MACOSX` folder only appears when the archive is unpacked at the command line.  If you unpack the zip file using the `unzip` command line utility, even on OSX it will appear, if you unpack by clicking on the zip in finder it does not. However creating an archive without the `__MACOSX` folder does not prevent you from unpacking it in this way. The same behavior is observed in the updated version you linked the only difference is that the `code` directory has slightly different permissions.

Actually the `__MACOSX` folder only appears in the archive when it is created in finder in the first place. If you create the archive using the `zip` utility at the command line it can be extracted at the command line on OSX/linux without the extra folder appearing *and* can still be opened by clicking on it in finder. I have no idea why doing the compression with finder puts it there but that is what I found. I have submitted a PR (#409) that fixes this.

**Comment by amjames** [comment]
@rgaiacs brings up a good point though. If the contents of the code directory were subject to some type of CI zip files could be automatically updated as the code changes.  Also having CI on the code is a good idea, since for example currently `arith.py`, `check.py`, and `line_count.py` are all technically broken as they still contain python2 print statements. I don't really know how nicely CI would play with github pages though.

**Comment by rgaiacs** [comment]
> I have no idea why doing the compression with finder puts it there but that is what I found.

Probably because finder default is to save everything that the user is going to need to have thumbnails inside the zip file.

> currently arith.py, check.py, and line_count.py are all technically broken as they still contain python2 print statements.

@amjames Can you open a issue for it.

**Comment by amjames** [comment]
@rgaiacs done #410

**Comment by pllim** [comment]
The `__MACOSX` is still there.

**Comment by pllim** [comment]
Oh, wait... You put the fixed ZIP file somewhere else, I see. Nope, can't even unzip the one at https://github.com/swcarpentry/python-novice-inflammation/blob/fix_zipfile/code/python-novice-inflammation-code.zip .

```
Archive:  python-novice-inflammation-code.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of python-novice-inflammation-code.zip or
        python-novice-inflammation-code.zip.zip, and cannot find python-novice-inflammation-code.zip.ZIP, period.
```
