### ISSUE TITLE
code and data ZIP files have different permissions

### ISSUE THREAD

**Issue by pllim** [swcarpentry/python-novice-inflammation#405]
After I unzipped both `python-novice-inflammation-code.zip` and `python-novice-inflammation-data.zip` on my Linux machine, I noticed that they have inconsistent file permissions:
```
drwx--S---. 2 username usergroup 2048 Jul 31 04:27 code/
drwxr-sr-x. 2 username usergroup 1024 May 10  2015 data/
```

**Comment by valentina-s** [comment]
Thanks for spotting this problem. I updated the permissions of the code folder (to all). Can you check if it works on Linux: https://github.com/swcarpentry/python-novice-inflammation/blob/fix_zipfile/code/python-novice-inflammation-code.zip

I can also add more permissions for the data folder.

**Comment by pllim** [comment]
Thanks, but unfortunately now I cannot even unzip it. `unzip` command on Linux now gives me this error:
```
Archive:  python-novice-inflammation-code.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of python-novice-inflammation-code.zip or
        python-novice-inflammation-code.zip.zip, and cannot find python-novice-inflammation-code.zip.ZIP, period.
```

The same command worked on the original archive.

**Comment by valentina-s** [comment]
Not sure what is wrong with that one as it opens on my laptop. Can you try this one submitted by @amjames https://github.com/swcarpentry/python-novice-inflammation/pull/409/files before I merge it. It removes the MACOSX folder and the permissions after unzipping on my laptop are drwxr-xr-x for the folder and -rw-r--r-- for each file. What permissions do you think we should aim for?

**Comment by pllim** [comment]
@valentina-s , yes, the version from @amjames works fine and has no extra `__MACOSX` folder. Thank you!
