### ISSUE TITLE
Code Samples have not been updated for python3

### ISSUE THREAD

**Issue by amjames** [swcarpentry/python-novice-inflammation#410]
The following files in `/code` still contain python2 `print` statements even though the course is advertised  as using python3.

- `arith.py`
- `line_count.py`
- `check.py` 

I haven't checked if there are any other python2->python3 changes that are needed.

**Comment by jokedurnez** [comment]
I made a pull request with a fix for this issue :)

**Comment by valentina-s** [comment]
I think this has been resolved. Thanks!
