### ISSUE TITLE
missing definition for `mutable` from glossary?

### ISSUE THREAD

**Issue by NickleDave** [swcarpentry/python-novice-inflammation#416]
Episode 3 has a link to the definition of `mutable` and `immutable`, and `immutable` itself says "See `mutable`", but there's no actual definition for `mutable`.

Guessing you would want some definition that's the opposite of the `immutable` definition. E.g., 
"Changeable. The value of mutable data can be altered after it has been created. See `immutable`."

I'd be happy to put in a PR to fix this, just let me know.

**Comment by tbekolay** [comment]
That definition looks good to me, if you could make a PR we would greatly appreciate it!

**Comment by dlm** [comment]
@tbekolay I was looking around for a newcomer-friendly way to help and found that this was open.  I added a PR for it:  https://github.com/swcarpentry/python-novice-inflammation/pull/500  Let me know what you think.

**Comment by maxim-belkin** [comment]
Closed in 35fd50d
Thanks, @dlm and @NickleDave !
