### ISSUE TITLE
Confusing names in the general form of a loop

### ISSUE THREAD

**Issue by tasospap21** [swcarpentry/python-novice-inflammation#419]
In the material, the general form of a loop is:

for element in variable:
    do things with element

However, the name variable for the collection/set of values is probably confusing for the audience. 

I would recommend changing this and also be consistent with the R course, where the naming is much better and clearer:
 
for variable in collection:
  do things with variable

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by tylerkelly13** [comment]
Agreed. Added pull request with suggested change.

**Comment by tbekolay** [comment]
Done in #423.
