### ISSUE TITLE
Key points in 06-func mentions stack frame/call stack, but these are not covered

### ISSUE THREAD

**Issue by shwina** [swcarpentry/python-novice-inflammation#424]
> Each time a function is called, a new stack frame is created on the call stack to hold its parameters and local variables.

> Python looks for variables in the current stack frame before looking for them at the top level.

**Comment by harpolea** [comment]
I agree that these two points should be reworded - in the lesson, there is an example which talks about variables defined inside the function not being 'known' outside of the function. This sort of language would be more appropriate than 'stack frame'.

**Comment by annefou** [comment]
I close this issue as it looks like it has been addressed. Please re-open if I am wrong.
