### ISSUE TITLE
Contribution-python-lesson

### ISSUE THREAD

**Issue by Laura-Gomez** [swcarpentry/python-novice-inflammation#431]
---

Episode: Analyzing data from Multiple Files. In the exercise: "Generate composite statistics"
The solution points to the path: data/inflamation*.csv
It should be: inflamation*.csv

Episode: Making choices. In the exercise "Sorting a list into buckets". 
It says: The folder containing our data files has large data sets whose names start with “inflammation-“, small ones whose names with “small-“
It should say: The folder containing our data files has large data sets whose names start with “inflammation-“, small ones whose names ***start*** with “small-“
The word start is missing

Episode: Command-Line Programs
In the first part, the code **$ head -4 inflammation-01.csv | python ../code/readings_04.py --min**
is not working.
The python script that has all functionalities is  ../code/readings_06.py

---

**Comment by richyvk** [comment]
Fixed some of this: https://github.com/swcarpentry/python-novice-inflammation/pull/432

**Comment by maxim-belkin** [comment]
All issues reported here have been resolved.
Thank you, Laura!
