### ISSUE TITLE
episode 4, last exercise - change to data path

### ISSUE THREAD

**Issue by kmichali** [swcarpentry/python-novice-inflammation#441]
Hi,
I propose a change to the Python lesson, episode 4, solution to the last exercise called "Generate Composite Statistics".

During the whole lesson the attendees are inside ~/Desktop/python_novice_inflamation/data/. Yet the solution to the exercise assumes that they are in ~/Desktop/python_novice_inflamation/.

I propose to change the solution to the exercise from:

import glob
import numpy
import matplotlib.pyplot

filenames = glob.glob('data/inflammation*.csv')

to:

import glob
import numpy
import matplotlib.pyplot

filenames = glob.glob('inflammation*.csv')

Cheers,
Katerina

**Comment by verdurin** [comment]
Yes, I've just encountered this. It was disconcerting to see an error and graphs with no output.
