### ISSUE TITLE
Where is jupyter notebook file?

### ISSUE THREAD

**Issue by robertbjornson** [swcarpentry/python-novice-inflammation#447]
Hi,

I'm trying to run the python lesson within a jupyter notebook.  I've downloaded and unzipped the files, but I don't see any jupyter notebook file (.ipynb).  When I run jupyter notebook in the data directory I basically just see the csv files.

I searched the github repo and see no .ipynb file there either.
 
Am I doing something wrong?

Thanks!

Rob

**Comment by yeemey** [comment]
When you run Jupyter, there's a 'New' button near the top right. Clicking on that gives you a dropdown menu to create a notebook (.ipynb file). After creating the notebook, you should see it in the directory as a .ipynb file.

**Comment by yeemey** [comment]
This may be helpful to add to the Setup page instructions.

**Comment by gcapes** [comment]
I'm submitting a PR for this.
