### ISSUE TITLE
Command-line section.

### ISSUE THREAD

**Issue by theboocock** [swcarpentry/python-novice-inflammation#45]
Using the sys module for the command-line is a little bit messy. I think it would be better to use the more powerful, and scalable command-line parser.

https://docs.python.org/2.7/library/argparse.html

I could rewrite the lesson to use this library if people think this is a good idea.

**Comment by gvwilson** [comment]
`argparse` and the like are out of reach of our beginners, but a pointer 
in `discussion.md` would be welcome.

**Comment by smilefreak** [comment]
I am not so sure, I personally find the sys arguments confusing, and bug-inducing. One reason is that everything has to be in the exact position, you cannot switch the arguments order as some may have realised is possible with all the shell commands earlier in the course. 

Also, the lesson also has an unconventional use of the --argument.

The options --max, --mean, and --min, should maybe be flagged like -a mean -a max -a min, or --action mean --action max --action min. That get's a little bit more complicated if we are using the sys arguments, but is easy with argparse.

```parser.add_argument('-a','--action',dest='action')
args = parser.parse_args()
args.action```

Do you really think this is too complex? 

If so, do you think it is worth fixing up the examples and challenges to make them a bit more realistic. The feedback I just received during the challenge session was about why you would even want to do this.

The first challenge about adding number 2 + 3 is a poorly designed problem, while it highlights the usage of sys there is nothing intuitive about why you would ever want to write a program like that.

**Comment by vahtras** [comment]
I do not think that it is an 'either/or' situation. I believe that the first introduction should be using the sys module. I still use that for quick and dirty scripts, mainly because I can never remember the correct syntax for argparse without looking up the documentation. On the other hand when the script grows and you have more than a few number of options or arguments, the sys module approach becomes messy indeed and an argparse solution is to prefer. Perhaps a real example to illustrate this? There a third alternative as well, docopt

https://pypi.python.org/pypi/docopt

**Comment by kynan** [comment]
I agree that starting with `sys.argv` makes sense and is not unrealistic for very simple use cases. However I'm not convinced `argparse` is way out of reach, as argued by @smilefreak. In fact it is a good exercise for reading and applying the docs.

I wouldn't introduce 3rd party libraries though @vahtras.

**Comment by kynan** [comment]
What was the decision on this @abostroem?

**Comment by abostroem** [comment]
I'm inclined to leave things as they are, I haven't heard a convincing case otherwise. I'll leave this open for a few days for additional comments.

**Comment by jiffyclub** [comment]
I agree that argparse is not a good use of time during the lesson. I know massively experienced Python programmers who have a hard time grokking argparse, it is not something you can throw out there and expect people to understand in a reasonable amount of time. It is pretty quick, however, to demonstrate how anything you put at the command line magically shows up in sys.argv. (It is magic, right?)

**Comment by jiffyclub** [comment]
FYI, [the lesson](http://swcarpentry.github.io/python-novice-inflammation/08-cmdline.html) already calls out argparse.

![screen shot 2015-04-29 at 2 42 46 pm](https://cloud.githubusercontent.com/assets/920492/7402096/130ff922-ee7e-11e4-8e67-2cb48a5799e0.png)
