### ISSUE TITLE
Episode 2 - Loops - Describing for-loops as iteration

### ISSUE THREAD

**Issue by LibraryViking** [swcarpentry/python-novice-inflammation#453]
Hello there!

I'm new to Python and to Software Carpentry, so this suggestion may be too beginner-oriented. When going through Episode 2 and starting the discussion on loops, the code is given as: 

```
word = 'oxygen'
for char in word:
     print(char)
```

The word `oxygen` is then printed out, letter by letter. 

When reading this for the first time, I thought that the variable `char` had some kind of command built into it to print each character one by one, since it's a shortened version of character. Then another block of code is given, showing that the `char` variable is mostly meaningless, since it really is just a variable. 

Unfortunately this left me feeling a bit confused by the entire thing, since I didn't understand how Python knew to print out each letter on a new line without any command aside from `for` and `print`.

This is likely just a gap in my own knowledge because I have little to no programming experience coming into this lesson, but since we may have students with that same level of experience, I wanted to start a discussion on ways to possibly improve this section. 

Could the section perhaps be updated to discuss iteration, and present the `for` loop as an iterator (introducing that concept as well)? The instructor could demonstrate code attempting to iterate on a string and a float, showing that only strings can be iterated on. I think that specifically introducing the `for` loop as an iterator (thus explicitly stating the built-in function of going character-by-character) could be less confusing for those new to the programming world.

**Comment by abtsubaki** [comment]
I agree with this - when I first started learning Python I had this exact same conundrum, not realising that 'char' is just a variable and you can actually make it anything, eg. x or ch or whatever. 
When I teach this, I re-do the for loop, using a different variable there.
Maybe, this could be introduced into the lesson, in order to make the fact that 'char' is just a variable name, more clear?

**Comment by jhidding** [comment]
Maybe the concept of iteration is a bit abstract to start with. An `iterator` is a specific thing in Python that is more generic than just for-loops; speaking of a for-loop as an `iterator` is correct in the broad sense of the English word, but incorrect when it involves more specific programming concepts.

Rather, I think, the concept of a linear collection as list-like objects (e.g. strings, ranges, numpy arrays (from chapter 1) ...) should be explained before for-loops. In this respect maybe the lists and loops chapters are the wrong way around, but switching them may lead to other problems. I assume people have thought about this before.

**Comment by sixpearls** [comment]
I just looked at this, and it seems like the list explanation only has one small example for-loop, and that may be as much a review as particularly insightful at this point.

I think list discussion would make sense to come first, and will create a pull request for that

**Comment by sixpearls** [comment]
Sorry all, I misunderstood the community practices for issues and pull request. This is my proposal for how to address the issue that @LibraryViking opened.

- swapping the order of the episodes 02-loop and 03-lists
- removing the for-loop example from the 03-lists 
- perhaps adding some explanation for how the ``for __ in ___:`` loop construction works, including the iterator variable and collection/iterator variable in the 02-loop

What do people think about that proposed changes?

**Comment by LibraryViking** [comment]
I like the changes suggested by sixpearls and jhidding, especially switching the episodes to have lists come before loops. A better explanation of the loop construction with an explanation of the built-in iterative part of the for-loop would be extremely helpful to folks not familiar with those programming concepts.

**Comment by rgaiacs** [comment]
> swapping the order of the episodes 02-loop and 03-lists

The change here is not simple. If you start with lists, learners will spend half an hour asking why they are learning data structure. If you start with loop but no knowledge of lists there aren't much that you can do. If you take the perspective of the full Software Carpentry workshop, learners would have get a introduction to loops in the shell lesson, I know this isn't the case in most of the workshops, with

```
for file in cubane.pdb  ethane.pdb  methane.pdb  octane.pdb  pentane.pdb  propane.pdb
do
wc $file
done
```

so the for-loop construction should be a little familiar.

**Comment by maxim-belkin** [comment]
Personally, I'd prefer to talk about basic and complex data types/structures in Python before loops.

The reasoning is simple: loops are used to apply the same code to all elements of a complex data structure. In this regard, loops a precursor to functions. And change to the story-line is straightforward: you gather some data (create a data structure) before you process it "one at a time". 

The fact that you can loop over a string is a nice "trick"... but, honestly, how often do we loop over strings one character at a time in real life? :)

**Comment by annefou** [comment]
Starting with data types/structures before loops is a classical approach in programming. It is very much like a software engineer approach so maybe this is what we should do in a Software Carpentry lesson (versus a Data Carpentry lesson).  However, I don't fully  understand why introducing data types/structures in Python before loops would help to clarify the described issue.

**Comment by jhidding** [comment]
I agree with sixpearls' suggestions. In other languages (like C) where for-loops are not 'collection-based' the current order of chapters would make more sense. In Python however, it is necessary to explain the the concept of collections and show the similarity between lists, strings and ranges. To clarify how it fixes the current issue: there seems to arise some confusion around iterating over a string as the first example of a loop. This is because it is a bad example; noone really iterates over a string like that. It's much more natural to talk about lists. The teacher then has more flexibility explaining what the different components of the for-syntax mean.

**Comment by sixpearls** [comment]
When I was practicing this lesson for the instructor training, I got caught at the introduction of the for-loop syntax. The iteration variable is easy to describe, but I wasn't sure how to explain the collection variable based on what was taught before. By teaching the concept of collections first, we can give a name (and meaning) to every part of the for-loop construction which would address the confusion @LibraryViking's brought up when opening the issue.

Besides, the loop lesson already presumes knowledge of lists/collections: the motivating examples for the loop require manipulating the string as a collection (with the selection syntax, which was introduced in the first lesson).

I would be happy to prototype these changes in the next few weeks.

Best,

**Comment by maxim-belkin** [comment]
Thanks, @sixpearls. Let us first decide how we can approach this.

1. Someone (@sixpearls, @LibraryViking, or anyone else) implements a "rough draft". We merge it and then slowly fix all the problems.

2. Given that the change will be rather significant, it will surely take some time. Because of that, it is not unreasonable to work on this in a separate branch (codename: `lists-first` or `1-3-2`) so that people can submit PRs against this branch. Once we're done, we can merge this branch back into `gh-pages`.

thoughts?
CC @MikeTrizna @annefou

**Comment by annefou** [comment]
Yes. That's what I wanted to suggest too. We have a number of issues & PR on loops/lists and it would be useful to come up and test one solution. Once we are happy with it we merge it to the main gh-pages.

**Comment by LibraryViking** [comment]
I'm still new to the Carpentries and Python in general, so if @sixpearls is willing I'd be happy to defer to his rough draft.

**Comment by maxim-belkin** [comment]
@annefou so, you're voting for the second option, correct?

@LibraryViking if we take the second approach, we'll create a second branch to which you will be able to contribute to. This second branch will not be merged into `gh-pages` until we're reasonably happy with it.

**Comment by annefou** [comment]
Yes @maxim-belkin,  I vote for the second option. Sorry I was not very clear!

**Comment by sixpearls** [comment]
A branch makes sense to me, I should be able to get to it in the next few weeks. If someone wants to get it started before then I'm fine with that too.

**Comment by maxim-belkin** [comment]
OK, I'll add a note here about the branch when we create it (I'd like to merge [swcarpentry/styles](https://github.com/swcarpentry/styles) first). It shouldn't take too long

**Comment by maxim-belkin** [comment]
I've created a new branch called `lists-loops`.  Please submit pull requests related to changing the order of episodes against that branch. I'm going to close this issue and create a new one with instructions how to contribute to this effort.

Thank you all for participating in this discussion!
