### ISSUE TITLE
Confusing exercise wording

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/python-novice-inflammation#454]
Ep1 check your understanding

> Draw diagrams showing what variables refer to what values after each statement in the following program:

It seems strange to request a diagram. Rather, 'write down what you expect the answer to be' would seem to be a more sensible wording?

**Comment by maxim-belkin** [comment]
Thanks @gcapes. I agree that drawing diagrams seems like an overkill though people might use them to get to the right answer

**Comment by maxim-belkin** [comment]
Thanks, @gcapes! :)
