### ISSUE TITLE
Pepper indexing analogy is incorrect in ep3 (lists)

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/python-novice-inflammation#458]
The last image should show the first grain of pepper for the analogy to hold. That's what `x[0][0]` would refer to. The current image is more an unordered representation of 
```
for i, ival in enumerate(x):
    for j, jval in enumerate(ival):
        print(x[i][j])
```
Which gives
```
pepper
zucchini
onion
cabbage
lettuce
garlic
apple
pear
banana
```

For the analogy to be useful, it shouldn't break down at the end.

**Comment by annefou** [comment]
It took me a while to understand your point! It's true that images do not fully match the text: list of grocery products versus pepper sachets. However the visual example is very good. Maybe this section  ("Nested lists") could be rework for instance using plant seeds (using sachets of sunflower, pumkin, tomatoes, etc.).

**Comment by gcapes** [comment]
Hi @annefou, my point isn't about pepper sachets vs grocery products. 

Rather, it's that the last visual example is completely wrong, which is shame because the first three are very good analogies. The last image doesn't match the subscript notation. `x[0][0]` would refer to one (and specifically, the first) grain of pepper. The image corresponding to `x[0][0]` shows all of the grains, unpacked from their container (list/pepper sachet) and in no discernible order.

**Comment by annefou** [comment]
@gcapes For me the first grain of pepper would be 'p' (first letter of 'pepper'): x[0][0][0]. I don't think it helps that the images do not match the text and this is why I suggested to rework it.

**Comment by gcapes** [comment]
:) We're talking at cross purposes here. 
You're using the lesson's definition of`x` which is a list of groceries. I'm talking just about the images, which are a general analogy for a list of lists. It just so happens that each sub-list (sachet) is the same.

Now, considering the images to be a general analogy for a list of lists and nothing to do with the previously defined list `x`, naming the pictures clockwise from the left:
The list of lists is a pepper pot containing a number of pepper sachets. Each sachets itself represents a single list, the pot full of sachets is the list of lists. This is picture 1.
The second image shows notation for referencing the first sub-list, and to return it as a list of lists -- the pot containing the single sachet is still a list of lists.
Picture 3 shows how to access a sub-list.
Picture 4 however, shows notation for referring to the first element of the sublist (the sachet). This would be a grain of pepper, not a pile of pepper grains i.e. the whole list unpacked. This is the only thing that needs changing, IMO.
