### ISSUE TITLE
What is wrong with the inflammation data?

### ISSUE THREAD

**Issue by karinlag** [swcarpentry/python-novice-inflammation#46]
I am preparing for teaching next week, and I have some questions:

1. Throughout the lesson, it is indicated that there is something wrong with the data. I have yet to figure out what exactly the problem is?

2. A more teaching technical thing: in 02 Checking our data, it is indicated that you can stuff the shown if statement into the for loop shown in 01 Processing multiple files. Do people do that when they teach, or do they just show them on screen and explain?

3. When I do put that if statement in there, I get either suspicious maxima or adding up to zero on all of them. Is this actually correct?

**Comment by gvwilson** [comment]
Hi Karin,

#3 is right - the data is synthetic (see tools/gen-inflammation.py), and 
as soon as you plot min/max, you can see the ramp and staircase.  
Learners get excited when we start talking about detecting fraud :-)

Cheers,
Greg

On 2015-02-21 12:10 PM, karinlag wrote:
>
> I am preparing for teaching next week, and I have some questions:
>
> 1.
>
>     Throughout the lesson, it is indicated that there is something
>     wrong with the data. I have yet to figure out what exactly the
>     problem is?
>
> 2.
>
>     A more teaching technical thing: in 02 Checking our data, it is
>     indicated that you can stuff the shown if statement into the for
>     loop shown in 01 Processing multiple files. Do people do that when
>     they teach, or do they just show them on screen and explain?
>
> 3.
>
>     When I do put that if statement in there, I get either suspicious
>     maxima or adding up to zero on all of them. Is this actually correct?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/python-novice-inflammation/issues/46>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by tbekolay** [comment]
Seems like this discussion should be added to `instructors.md`. If anyone's keen, assign yourself this issue; otherwise, I'll get to it before the 5.3 release.
