### ISSUE TITLE
Ep 05 'Sorting a list into Buckets' - solution should use clues given

### ISSUE THREAD

**Issue by gcapes** [swcarpentry/python-novice-inflammation#464]
> Add code to the template below to do this. Note that the string method startswith returns True if and only if the string it is called on starts with the string passed as an argument.

Yet the solution uses the `if x in y` notation instead, so there seems no reason to have mentioned the `startswith` method. Given the `x in y` notation hasn't been introduced, I propose changing the solution to use the `startswtih` method.

**Comment by cleebp** [comment]
I think this change is needed - I just created a [pull request](https://github.com/swcarpentry/python-novice-inflammation/pull/468) to change the solution code to use the startswith command over the 'if x in y' style previously being used.

**Comment by gcapes** [comment]
See also #465, of which your PR is a duplicate ;)

**Comment by gcapes** [comment]
No worries! It's just waiting for a maintainer to look at it.
