### ISSUE TITLE
Small mods to "Analyzing Patient Data" lesson

### ISSUE THREAD

**Issue by decaelus** [swcarpentry/python-novice-inflammation#474]
Dear SWC,
Having just the  trainer training workshop, I've been asked to contribute to a lesson to complete the training. I'm a little unclear about how to contribute and to which lesson to contribute, but I read through the "Analyzing Patient Data" lesson to see if I could help with anything. I think there are a number of small clarifications (and punctuation corrections) that might add value to the lesson. If I fork the repo, make the changes, and then make a pull request, would this satisfy the requirement for the trainer training?

Thanks,
Brian

**Comment by annefou** [comment]
Dear Brian,

If you would like to make punctuation corrections or clarifications to our lesson, you are more than welcome to fork the repo and make a pull request. Even though the lesson is quite mature, we still find typo or unclear statements and I am sure that would satisfy the requirement for the trainer training. 
Thanks for your efforts.
Anne.
