### ISSUE TITLE
Improve consistency of teaching flow

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/python-novice-inflammation#48]
@moorepants and @zonca [reported](http://software-carpentry.org/blog/2015/02/instructor-debriefing-2015-02-24.html) that

> We tried the 5.3 Beta Python and it was a little rough around the edges. (...) it has big issues, like functions being introduced in lesson 4 but used in 2.

**Comment by abostroem** [comment]
@r-gaia-cs are the other issues listed somewhere? Can you either point me to them or elaborate?

**Comment by r-gaia-cs** [comment]
> are the other issues listed somewhere? Can you either point me to them or elaborate?

@moorepants and @zonca could you elaborate the others issues that you find? Thanks in advance.

**Comment by zonca** [comment]
thank you @r-gaia-cs , @abostroem, other issue are mainly formatting:

* output in defining default: http://swcarpentry.github.io/python-novice-inflammation/06-func.html
* some FIXME at the end of: http://swcarpentry.github.io/python-novice-inflammation/03-lists.html
