### ISSUE TITLE
Simple exercise to differentiate print vs return

### ISSUE THREAD

**Issue by maxim-belkin** [swcarpentry/python-novice-inflammation#506]
We should probably add the following simple exercise somewhere:
```
print(print(1))
```

**Comment by tlvdberg** [comment]
Hi Maxim!
I made an exercise for learning the difference between return and print. I will submit a pull request. You can see if you like it, and merge it or not. 
Let me know if you would rather like any changes. Let me know if something's not as it should be, I'm new to this. 
I will make it part of my check-out exercise(s). I already made some other small contributions, but am not sure that'll be enough.
Best regards,
Tineke

**Comment by maxim-belkin** [comment]
Hi Tineke! Thank you for the note! As for the instructor checkout - size (of the PR) does not matter. Even a one-word change counts.

**Comment by maxim-belkin** [comment]
Closed in #524
