### ISSUE TITLE
Ch-Ch-Ch-Changes

### ISSUE THREAD

**Issue by crocodoyle** [swcarpentry/python-novice-inflammation#513]
In lesson 3, there is a box that incorrectly quotes David Bowie's song Changes. There should be one more "Ch-". 
Source: https://youtu.be/6fKRgyd6NGg?t=53s

**Comment by maxim-belkin** [comment]
OMG! Thanks for the report, Andrew! Apparently, we've been [livin' on the edge](https://www.youtube.com/watch?v=7nqcL0mjMjw)! Do you want to submit a PR? :)
