### ISSUE TITLE
Zipped code file contains Python 2 syntax (at least as linked in the lesson website)

### ISSUE THREAD

**Issue by tlvdberg** [swcarpentry/python-novice-inflammation#518]
A few months ago I noticed print statements in the code files that I downloaded contain Python 2 syntax. Now I just checked this in the repo, but here syntax has been corrected in the print statements, in order to comply with Python 3. 
Now I also just checked the download that is linked to in the lesson setup webpage (http://swcarpentry.github.io/python-novice-inflammation/setup/) has Python 2 syntax in the print statements, therefore giving an error when run during a lesson (That are explicitly done in Python 3).

Is the link incorrect, or is the zipped file not updated to Python 3 code?

---

**Comment by maxim-belkin** [comment]
Hi @tlvdberg! Thanks for the report!
Yes, apparently there is a discrepancy between files in the `/code` directory and those in the zip archive: zip file has Python 2 code.
