### ISSUE TITLE
Lesson #1 - editing objective order and language

### ISSUE THREAD

**Issue by tpatwood** [swcarpentry/python-novice-inflammation#575]
My first thought is that the objectives should mirror what we'll be doing in the lesson! A suggested order with some wordsmithing: 

- Define a _variable_ in Python.
- Assign a value to a variable. 
- Explain the importance of libraries.
- Import a Python library and use it to read and display data from a file. 
- Use functions to display particular characteristics of data contained in a file.
- Use functions from a library to manipulate data contained in a file.
- Plot simple graphs from data.

(I think that objectives 5 and 6 could even be conflated: Use functions to display characteristics and manipulate data contained in a file.)

Additionally -- and this might just be me -- I'd argue that introducing the Python interpreter as a calculator as the very first introduction to Python can be distracting (it's kind of fun to play around with Python and get it to print things, especially if we've just come off learning about the shell). I'd suggest starting the "Variables" section by cutting out the two sentences before "To do anything useful with data..." Then introduce Python's ability to be a calculator in the section "Using Variables in Python" in the third line: "Moreover, we can do arithmetics with variables right inside the print function -- because Python has the basic functions of a calculator as well" (or something more eloquently worded).

**Comment by maxim-belkin** [comment]
Seems interesting and, in general, reasonable. Please feel free to submit Pull Requests that implement what you propose here. 

I also wonder what other maintainers and instructors think about the "Python interpreter as a calculator" intro.

**Comment by annefou** [comment]
The section about "Python interpreter as a calculator" is very short and is used to help novice to understand why variables are useful (not only to store a value but to store the result of some computations). 
I guess I am biased as I am working in environmental sciences where we use programming to solve "physics equations". I agree it may be disturbing for others but @tpatwood what would you suggest?

**Comment by tpatwood** [comment]
After working through this a few times, I changed my mind. I like this section! It is short and a nice little intro into working with Python, and helps you flow into the next parts of the lesson.

**Comment by annefou** [comment]
Great! So I guess we can close this issue, isn't it?
