### ISSUE TITLE
Add link to data files?

### ISSUE THREAD

**Issue by BernhardKonrad** [swcarpentry/python-novice-inflammation#60]
I'm not sure of the intention of the html version, but wouldn't it make sense include a direct link to the csv data files? That way students can work on this tutorial at their own pace without having to clone the repository?
See also #9.

**Comment by r-gaia-cs** [comment]
> I'm not sure of the intention of the html version

Because we use GitHub Pages to host the HTML version and GitHub Pages can't compile Markdown using Pandoc.

> wouldn't it make sense include a direct link to the csv data files?

Yes. I thought that I did fixed it once but couldn't find the commit. =(

> That way students can work on this tutorial at their own pace without having to clone the repository?

+1

**Comment by iglpdc** [comment]
What I do usually to avoid the students having to clone the repo is to make a zip with the files needed in each lesson and put a link in the workshop website (see [here](http://iglpdc.github.io/2015-04-01-wcmc/), at the end of the "General info" section). Maybe we could provide a script that makes the zip and adds the links, so it's faster if the instructor needs/wants to do it.In my experience, specially for the shell lesson, it's tricky to have git working in all computers.

**Comment by wking** [comment]
On Wed, Apr 08, 2015 at 08:19:36AM -0700, Ivan Gonzalez wrote:
> What I do usually to avoid the students having to clone the repo is
> to make a zip with the files needed in each lesson…

You can create a Git repository and have GitHub (or whatever hosting
site) build the zip automatically.  For example, see
efran/2015-04-09-UW#16, [1], and [2].  We're not taking this route for
UW, but I still think it's the best-of-both-worlds approach.

[1]: https://github.com/wking/2015-04-09-UW-data
[2]: https://github.com/wking/2015-04-09-UW-data/archive/master.zip

**Comment by BernhardKonrad** [comment]
Thank you for these answers. You are right, for workshops the instructor can always provide alternative ways (git clone or zip download). Making this easier and more obvious for instructors may be worthwhile in its own right.

I was more thinking about the use of the lecture material outside or after a workshop as a learning resource. For starters, maybe a link to the corresponding `data` folder would be sufficient: https://github.com/swcarpentry/python-novice-inflammation/tree/gh-pages/data?

**Comment by wking** [comment]
On Wed, Apr 08, 2015 at 10:22:53PM -0700, Bernhard Konrad wrote:
> I was more thinking about the use of the lecture material outside or
> after a workshop as a learning resource. For starters, maybe a link
> to the corresponding `data` folder would be sufficient:
> https://github.com/swcarpentry/python-novice-inflammation/tree/gh-pages/data?

I'd still stick with something that could be cloned or downloaded as a
zip.  For example, folks following the shell lesson (or anyone with a
lot of data files) won't want to download them one by one from
GitHub's tree browser.

**Comment by gvwilson** [comment]
@BernhardKonrad can you PR against the current repo?
