### ISSUE TITLE
Change the data type used to explain loops

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/python-novice-inflammation#624]
I cringe every time I see the concept of loops explained using a string data type.  While strings can be accessed using index notation, there are issues with it as described later in the lesson (i.e. a string cannot be written to using index notation). I hesitate to introduce and describe a major concept (loops) using an example that is only rarely used (iterating characters in a string), especially since there are other faster methods for working with strings.

I propose to change the example for loops from a string to a list. An example of this change is in this lesson https://kekoziar.github.io/python-novice-inflammation/02-loop/

This change may also be implemented in conjunction with issue #496, and might best be implemented with the concept swap, since #496 would allow introduction of the list concept prior to using it in loops.

**Comment by annefou** [comment]
Yes, your proposal does not make sense with the current order (loops and then lists) but would certainly be meaningful if lists are introduced before loops.

**Comment by kekoziar** [comment]
Suggestions implemented w/PR#626.  Thanks for your feedback!
