### ISSUE TITLE
Lesson 2 - drafting of intro text

### ISSUE THREAD

**Issue by HeatherAn** [swcarpentry/python-novice-inflammation#666]
At the beginning of the lesson it says: 'In the last episode, we wrote some code that plots some values of interest from our first inflammation dataset, and reveals some suspicious features in it, such as from inflammation-01.csv'. Here I would suggest changing it to: 'In the last episode, we wrote some code that plots values of interest from our first inflammation dataset (inflammation-01.csv), which revealed some suspicious features in it'.

**Comment by maxim-belkin** [comment]
Hi @HeatherAn. Good suggestion! Please submit a PR with your proposed changes (and let me know if you need any help with that). I also wonder if "some" in front of "code" is necessary... Can we replace it with "Python"?

**Comment by HeatherAn** [comment]
Replacing "some code" by "Python code" seems ok. I will submit a PR to change the text then!
