### ISSUE TITLE
Lesson 3 - change index in exercise

### ISSUE THREAD

**Issue by HeatherAn** [swcarpentry/python-novice-inflammation#667]
In lesson 3, after the 'Turn a String Into a List' exercise, there is a code that slices the binomial_name. There it says: species = binomial_name[11:24], which doesn't lead to any errors. However it might be confusing for students since the string ends at position with index 22. So I would suggest to change it to 'species = binomial_name[11:23]', or point out why using ending index 24 instead of 23 does not cause an error.

**Comment by maxim-belkin** [comment]
Thanks, @HeatherAn. This issue has been resolved in #678.
