### ISSUE TITLE
Lesson 8 - suggestion to change text

### ISSUE THREAD

**Issue by HeatherAn** [swcarpentry/python-novice-inflammation#673]
In lesson 8 'Assertions' section, it says 'the post-conditions on lines 17 and 18 help us catch bugs by telling us when our calculation cannot have been correct'. I guess there is a typo ('cannot have been correct'). Suggestion: modify to 'when our calculations are not correct'.

**Comment by maxim-belkin** [comment]
how about `might have been incorrect`?
