### ISSUE TITLE
Lesson 3 - slicing the list/string.

### ISSUE THREAD

**Issue by drshrirang** [swcarpentry/python-novice-inflammation#676]
As string binomial_name has "Drosophila melanogaster"
indexed from 0 to 22 i.e. 23 characters.Thus the slice I feel 
should be from [11:23] and not [11:24].

However if you write 

species = binomial_name[11:24]
you can include the comment
> an index  which is of larger size will be reduced to the string length

The link is :http://swcarpentry.github.io/python-novice-inflammation/03-lists/index.html

**Comment by maxim-belkin** [comment]
Thanks, @drshrirang! Yes, it should be `11:23`, not `11:24`. 
I think this error went undetected for the reason you mention (upper limit of a slice can exceed the index of the last element. Please submit a PR to change 24 to 23 (let me know if I can help you with that in any way).
Again, thank you!
