### ISSUE TITLE
Remove paragraph about %matplotlib inline magic 

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/python-novice-inflammation#716]
Since IPython kernel [4.4.0](https://github.com/ipython/ipykernel/blob/master/docs/changelog.rst#440), we don't need the `%matplotlib inline` magic anymore as mention in the log file:

> - Use MPLBACKEND environment variable to tell matplotlib >= 1.5 use use the inline backend by default. This is only done if MPLBACKEND is not already set and no backend has been explicitly loaded, so setting MPLBACKEND=Qt4Agg or calling %matplotlib notebook or matplotlib.use('Agg') will take precedence.
> - Select inline matplotlib backend by default if %matplotlib magic or matplotlib.use() are not called explicitly (for matplotlib >= 1.5).

**This is a good bug for novices.**

# Instructions for novices

1. Open the file `01-numpy.md`
2. Locate and remove the "Some IPython Magic" call out box.
3. Commit and send your pull request.

**Comment by Iain-S** [comment]
Hello.  Please see pull request #733 for a fix.
