### ISSUE TITLE
Update images generated by matplotlib

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/python-novice-inflammation#717]
The image that we have at the lesson is

![old](https://user-images.githubusercontent.com/1506457/64918770-43cc7c00-d779-11e9-8c4b-8f4dbee26b3c.png)

When I was reviewing the lesson using matplotlib 2.2.2 and 3.0.3, the image that I generate was

![new](https://user-images.githubusercontent.com/1506457/64918786-61014a80-d779-11e9-8c3c-2bea6394add6.png)

@fmichonneau do you have a suggestion for how to fix this?

**Comment by fmichonneau** [comment]
could we do a PR to update the images? I don't quite have the bandwidth needed at this time to test if we could use reticulate for this lesson, so it would have to be a manual process at this time.

**Comment by maxim-belkin** [comment]
Thanks for the report, Raniere.
We'll take care of figures.

**Comment by nanjiangshu** [comment]
Hi, 

The line color should be specified literally as blue in order to make sure the images will have consistent line color. e.g.

```
min_plot = matplotlib.pyplot.plot(numpy.min(data, axis=0), 'b')
matplotlib.pyplot.show()
```
I have also made a pull request at 
https://github.com/swcarpentry/python-novice-inflammation/pull/718

**Comment by maxim-belkin** [comment]
I've updated the figures in #719.
