### ISSUE TITLE
Tuples and Exchanges challenge throws an error (with fix)

### ISSUE THREAD

**Issue by janetriley** [swcarpentry/python-novice-inflammation#72]
In [05-cond.md](https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/05-cond.md), this section:

```
Tuples and exchanges
Explain what the overall effect of this code is:

temp = left
left = right
right = temp
```

produces this error:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-199-42933dda7154> in <module>()
----> 1 temp = left
      2 left = right
      3 right = temp

NameError: name 'left' is not defined
```

`left` and `right` should be initialized to prevent the error. 

[Pull request here](https://github.com/swcarpentry/python-novice-inflammation/pull/73).

**Comment by tbekolay** [comment]
Hmm. My interpretation of this challenge was that it was not meant to be executed; it's asking the student to mentally simulate what this code would do, regardless of the actual value that `left` and `right` point to. Being able to say what it does for one example is not really what we want, we want the student to think of it at a higher level. That is, a correct answer would be "it swaps what is in `left` and `right`", but "`right` would be `'L'` and `left` would be `'r'`" would not be a full answer even though it would be true for a particular example. If a student wishes to put it in the interpreter to see what it does, then I would tell them to make `left` and `right` be whatever they want.

That's a pedagogical preference / style though... I can also see the argument for including a particular example, even though we want the student to answer more generally. So, could other instructors that have taught this (or a similar) lesson chime in on whether we should initialize these variables?

**Comment by kynan** [comment]
I use this as an abstract example. It's straightforward to understand without the variables being initalized I think.

**Comment by abostroem** [comment]
I had the same thought as @janetriley. I think it is useful to give students a concrete example (that they can execute) and then ask them to abstract from there.
