### ISSUE TITLE
Episode 11 - command line, keypoints

### ISSUE THREAD

**Issue by k-dominik** [swcarpentry/python-novice-inflammation#764]
Dear swcarpentry team,

while I was going through the episdodes I stumbled over the last keypoint of the last episode (https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/_episodes/11-cmdline.md)

In the end you mention `sys.stdout` as on of the keypoints. It is, however, not mentioned once in the text. I understand the urge to mention the counterpart of `sys.stdin`, but maybe it would be better to leave it out completely, or, preferrably explain it in the text.

Cheers!

**Comment by ldko** [comment]
@k-dominik thanks for catching that. I think it makes sense to remove the keypoint rather than trying to fit in an explanation/example in the episode at this point. What do you think @annefou @maxim-belkin ?

**Comment by annefou** [comment]
Definitely right! I would also remove it.

**Comment by maxim-belkin** [comment]
Agreed -- the keypoint has to go. It looks like it was never covered in the lesson (at least I couldn't find it).
Thank you, @k-dominik!

**Comment by ldko** [comment]
@k-dominik would you be willing to open a pull request to remove the keypoint?

**Comment by k-dominik** [comment]
thank you @ldko, @annefou, @maxim-belkin for your comments! I proceeded to open a PR (#768) that implements your consensus of removing the reference to `stdout` altogether.
