### ISSUE TITLE
Call for Contributions: image descriptions & titles

### ISSUE THREAD

**Issue by maxim-belkin** [swcarpentry/python-novice-inflammation#781]
### Overview 

We'd like to solicit contributions aimed at improving image descriptions (also known as "alternative text") in our lesson. The goal of this solicitation is to lower barriers to using Python Novice Inflammation lesson for learners with vision impairments and those who are unable to clearly see images for other reasons.

### Technical details

Our lesson is written in the Markdown language. Therefore, all images follow the same format:

```markdown
![image description](../fig/image.png "Optional title")
```

This call seeks contributions aimed at improving the text in square brackets above (`image description`).

### Current list of figures

- [x] 01-intro.md  >  `![Variables as Sticky Notes](../fig/python-sticky-note-variables-01.svg)`
- [x] 01-intro.md  >  `![Creating Another Variable](../fig/python-sticky-note-variables-02.svg)`
- [x] 01-intro.md  >  `![Updating a Variable](../fig/python-sticky-note-variables-03.svg)`
- [x] 02-numpy.md  >  `![Zero Index](../fig/python-zero-index.png)`
- [x] 02-numpy.md  >  `![Operations Across Axes](../fig/python-operations-across-axes.png)`
- [x] 03-matplotlib.md  >  `![Heatmap of the Data](../fig/inflammation-01-imshow.svg)`
- [x] 03-matplotlib.md  >  `![Average Inflammation Over Time](../fig/inflammation-01-average.svg)`
- [x] 03-matplotlib.md  >  `![Maximum Value Along The First Axis](../fig/inflammation-01-maximum.svg)`
- [x] 03-matplotlib.md  >  `![Minimum Value Along The First Axis](../fig/inflammation-01-minimum.svg)`
- [x] 03-matplotlib.md  >  `![The Previous Plots as Subplots](../fig/inflammation-01-group-plot.svg)`
- [x] 03-matplotlib.md  >  `![Plot with step lines](../fig/inflammation-01-line-styles.svg)`
- [x] 04-loop.md  >  `![Analysis of inflammation-01.csv](../fig/03-loop_2_0.png)`
- [x] 04-loop.md  >  `![loop_image](../fig/loops_image.png)`
- [x] 05-lists.md > `![The first element of a list. Adapted from @hadleywickham.](../fig/indexing_lists_python.png)`
- [x] 06-files.md  >  `![Analysis of inflammation-01.csv](../fig/03-loop_49_1.png)`
- [x] 06-files.md  >  `![Analysis of inflammation-02.csv](../fig/03-loop_49_3.png)`
- [x] 06-files.md  >  `![Analysis of inflammation-03.csv](../fig/03-loop_49_5.png)`
- [x] 07-cond.md  >  `![Executing a Conditional](../fig/python-flowchart-conditional.png)`
- [x] 08-func.md  >  `![The Blueprint for a Python Function](../fig/python-function.svg)`
- [x] 10-defensive.md  >  `![Overlapping Ranges](../fig/python-overlapping-ranges.svg)`

Ideally, image description would explain (describe) an image and its purpose in the lesson. To learn more about best practices for writing good image descriptions, go to https://webaim.org/techniques/alttext

If you'd like to improve the description of one of the images in our lesson, please submit a Pull Request or reply here with your suggestions and we'll be happy to help you with submitting a request.

**Comment by blankdots** [comment]
shouldn't the `![The first element of a list. Adapted from @hadleywickham.](../fig/indexing_lists_python.png)` in `05-lists` be included as well ?

**Comment by maxim-belkin** [comment]
Thank you, Stefan!

**Comment by spikelynch** [comment]
Just created the above pull request with an alt-text for an image in lesson 4 as part of my trainer checkout procedure.

**Comment by lc822** [comment]
Suggestion for 06-files.md `![Analysis of inflammation-01.csv](../fig/03-loop_49_1.png)`:
Output from the first iteration of the for loop. Three line graphs showing the daily average, maximum and minimum inflammation over a 40-day period for the patients in inflammation-01.csv.

Happy to hear your feedback/suggestions.

**Comment by ldko** [comment]
Hi @lc822 ,
Thanks for suggesting new alt text for the line graph figure of inflammation-01.csv in the files episode. I like what you have suggested here, which I think provides an adequate description in the context of the surrounding text of the page. If you have a chance, we would be happy to have you open a pull request.

**Comment by lc822** [comment]
Great, I have done so (#908)

**Comment by ivastar** [comment]
Suggestions for the remaining image descriptions in 03-matplotlib.md, consistent with the one offered in #908: 

03-matplotlib.md > ![A line graph showing the average inflammation across all patients over a 40-day period for the patients in inflammation-01.csv.](../fig/inflammation-01-average.svg)
03-matplotlib.md > ![A line graph showing the maximum inflammation across all patients over a 40-day period for the patients in inflammation-01.csv.](../fig/inflammation-01-maximum.svg)
03-matplotlib.md > ![A line graph showing the minimum inflammation across all patients over a 40-day period for the patients in inflammation-01.csv.](../fig/inflammation-01-minimum.svg)
03-matplotlib.md > ![Three line graphs showing the daily average, maximum and minimum inflammation over a 40-day period for the patients in inflammation-01.csv.](../fig/inflammation-01-group-plot.svg)
03-matplotlib.md > ![Three line graphs showing the daily average, maximum and minimum inflammation over a 40-day period for the patients in inflammation-01.csv with step lines connecting the points.](../fig/inflammation-01-line-styles.svg)

**Comment by ldko** [comment]
Hi @ivastar ,
Thank you for proposing these image descriptions. I think they are fitting in that they give more description than what we currently have, and details of the images you are describing are supplemented by the text before and after the images (for example, what the lines displayed are doing). I think we could leave off "for the patients in inflammation-01.csv" in the descriptions to keep the text shorter, because we are using the same data set throughout the episode, and because the file reference is not explicit in the images. We welcome a pull request! thanks again!

**Comment by vinisalazar** [comment]
I hope this is okay, but I went ahead and implemented the titles suggested by @ivastar with a few tweaks.

Best,

V

**Comment by vinisalazar** [comment]
I've also submitted a second PR providing suggestions for the remaining figures listed by OP. I hope it helps!

Thank you,

V

**Comment by ivastar** [comment]
@vinisalazar sure, no problem.
