### ISSUE TITLE
Adding type hints example to functions

### ISSUE THREAD

**Issue by blankdots** [swcarpentry/python-novice-inflammation#790]
This is not necessary a new idea and yes I am aware that the contributing guidelines state that:
> Our lessons already contain more material than we can cover in a typical workshop, so we are usually not looking for more concepts or tools to add to them. 

I looked if there was some existing issue/PR on this but could not find it, and if there is already one please let me know.

I think the `Creating Functions` part of this lesson should at least contain some information about typing and have been part of Python since 3.5 and will and has been included in the standard library on a provisional basis https://docs.python.org/3.6/library/typing.html . Even thought this might not look like a novice concept I think should be at least mentioned as some developers adopt it in their source code and coming across this would be beneficial.

Building on the example function:
```
def fahr_to_celsius(temp):
    return ((temp - 32) * (5/9))
```

A similar function with typing would look like:
```
def fahr_to_celsius(temp: float) -> float:
    return ((temp - 32) * (5/9))
```
An estimated time to introduce and talk about this concept would be ~5 minutes. I think the concept should be briefly mentioned with pros and cons should not go into much detail of `typing`, and it can be part of `How can I define new functions?` or it can be added at the end of the lesson as: Other ways of defining a function.
As for how we can make room for this as it is new content, not sure at this point but I can think more on this if there is interest.

I am willing to do a PR on this if there is interest.

**Comment by ldko** [comment]
@blankdots thank you for taking the time to open an issue to bring up `typing`. As the lesson is targeted to non-developers with novice programming skills, at this point in time, my personal opinion is that `typing` would be too much to include in the main episodes . Some of my reasoning is: 
* type hints are optional and frequently not  used
* while type hints would make sense to developers with background in languages that require declared types, it may be a lot to absorb for someone learning functions for the first time
* in about 5-6 hours of teaching Python, there are a lot of things we don't have time to cover, some of them more likely to be seen than type hints
* it would be something mentioned but not made use of in the functions we continue to write as the lesson progresses, which makes it perhaps not worth the time and added layer of complexity to introduce

One option for including type hints in the lesson could be to put it into the [extras section](http://swcarpentry.github.io/python-novice-inflammation/extra_material/), for those who want more information.

Perhaps we can get further discussion from other maintainers @maxim-belkin @annefou and the greater community on this topic.

**Comment by maxim-belkin** [comment]
Thanks for the suggestion, Stefan.

>  I think the concept should be briefly mentioned with pros and cons should not go into much detail of `typing`, and it can be part of `How can I define new functions?` or it can be added at the end of the lesson as: Other ways of defining a function.

- Could you please list the cons and pros of typing that you mention above?
- Which episode are you suggesting we add it to?
- Our learners use either plain vanilla Python interpreter, IPython, or Jupyter notebooks. How can we demonstrate typing using any of these interpreters?*

 <sup>*</sup>Note that Python documentation (https://docs.python.org/3.8/library/typing.html) says:
> **Note:** The Python runtime does not enforce function and variable type annotations. They can be used by third party tools such as type checkers, IDEs, linters, etc.

**Comment by blankdots** [comment]
Thank you for your feedback!

@ldko I think I might not have explained my idea well enough. 
The comments you made make perfect sense.
One thing still to keep in mind is that case where a novice might encounter a different structure of a function than that is taught as part of the lesson, and that will not take much from a lesson to mention that a function might look a bit different.

My suggestion was to included only in the [Create functions](http://swcarpentry.github.io/python-novice-inflammation/08-func/index.html)] part, not all the main episodes, but `extra_material`, as you proposed, sounds also good.

@maxim-belkin 
> Which episode are you suggesting we add it to?

 [Create functions](http://swcarpentry.github.io/python-novice-inflammation/08-func/index.html) but [extra_material](http://swcarpentry.github.io/python-novice-inflammation/extra_material/) as @ldko suggested sounds good.

> Our learners use either plain vanilla Python interpreter, IPython, or Jupyter notebooks. How can we demonstrate typing using any of these interpreters?

In my tests I did not run into any issues using vanilla python 3.6/3.7 or Jupyter, but let me know if you encountered something that does not work. I might have missed something.

> Could you please list the cons and pros of typing that you mention above?

- [pro] first point is related to the note that you got of Python 3.8 documentation, related to IDEs and linters, meaning it makes it easier for them to detect any issues/bugs with the code related to e.g. data validation and quality of code. Or at least that is how I interpret that note.
- [pro or con] this is on the edge as for some people it might make code more readable for others not. 
- [pro] in bigger projects it might offer more insight into how types flow through the code and, from my point of view, it does make for a more maintainable code and architecture.
- [con] they have little value in throwaway scripts 
- [con] they do take a lot of time to add

**Comment by maxim-belkin** [comment]
Thank you for your answers, Stefan.
Below are my responses.

---

> > Our learners use either plain vanilla Python interpreter, IPython, or Jupyter notebooks. How can we demonstrate typing using any of these interpreters?
> 
> In my tests I did not run into any issues using vanilla python 3.6/3.7 or Jupyter, but let me know if you encountered something that does not work. I might have missed something.

How exactly did you _test_ typing feature in plain vanilla Python / Jupyter? According to the documentation, plain vanilla Python interpreter does not enforce type annotations. I believe Jupyter does not do that either, does it?

>    * [pro] first point is related to the note that you got of Python 3.8 documentation, related to IDEs and linters, meaning it makes it easier for them to detect any issues/bugs with the code related to e.g. data validation and quality of code.

- How can we demonstrate this in our lesson?
- We don't talk about "quality of code". Can you clarify what you mean here?

**Comment by blankdots** [comment]
@maxim-belkin good questions, let me see if I can clarify.

> How exactly did you test typing feature in plain vanilla Python / Jupyter? According to the documentation, plain vanilla Python interpreter does not enforce type annotations. I believe Jupyter does not do that either, does it?

I think there was some confusion, and I will refer to my original suggestion: illustrate that a function can have a different structure without going into too much detail regarding `typing`. The code on https://docs.python.org/3.7/library/typing.html will run in Python / Jupyter and can be run as is, that is what I tested.

But In order to demonstrate advance usages as per your questions, a package such as `mypy`  would be required in order to demonstrate more insights into type checking or an linter that supports that e.g. https://github.com/microsoft/pyright or an editor PyCharm or any other that is similar.

Jupyter not sure what that would require for an advanced example, but pretty sure it is possible.

> How can we demonstrate this in our lesson? 

I think coming up with examples would take more time, but first thought is that there are already packages that can be used (some mentioned above) to demonstrate.

> We don't talk about "quality of code". Can you clarify what you mean here?

This is fairly subjective, I recognise, and will give you my personal view on it as multiple dimensions of assessing code quality might be relevant reliability (runs without issues and produces the right output), maintainability (related to easy source code can be understood: structure, complexity etc.), testing etc.

But I would argue that there is reference to "quality code", without directly referring mentioning it in http://swcarpentry.github.io/python-novice-inflammation/10-defensive/index.html episode. There is a correlation between TDD and code quality or at least in my opinion.

**Comment by ldko** [comment]
@blankdots , we appreciate your further explaining your position; you do make valid points about how showing learners type hints could have some value.

We had a chance to talk about the pros and cons of adding type hints to the lesson material at a maintainers meeting this week and determined that the cons outweigh the pros at this time. Since type hints are not required and add a greater complexity to writing code, they would add unneeded cognitive load for many of our learners who are new to programming and are not working toward becoming professional developers. As far as teaching the concept, many of us teach the lesson in Jupyter Notebook where the type hints are not enforced, which makes it difficult to show the value add.  In addition to these cons, us maintainers are working under a guideline of not introducing new concepts without strong justification and without removing other material to allow teaching time.

Again, thanks for proposing this change, we hope you will consider making other contributions in the future.

**Comment by blankdots** [comment]
it is ok, I understand. Thank you for considering it :)

**Comment by maxim-belkin** [comment]
Thank you for the suggestion and understanding, Stefan. As Lauren said, we definitely agree with you that there is value in learning about type hints but our learners and tools are not ready for it yet. Perhaps, the list of topics we do not teach in this lesson will inspire someone to create a Python lesson on these topics.
