### ISSUE TITLE
Is there interest in an upgrade to Python 3?

### ISSUE THREAD

**Issue by jni** [swcarpentry/python-novice-inflammation#81]
Hi all,

There's some hints [here](http://python-notes.curiousefficiency.org/en/latest/python3/questions_and_answers.html#but-name-says-python-3-was-a-waste-of-time-didn-t-help-made-things-worse) that @gvwilson wasn't pleased with the Python 3 transition, but that he now believes it is no harder to teach than Python 2. (I haven't found a primary source for these comments.)

I think every beginner we teach Python 2 puts additional load on the community (which has to maintain Python 2 code for that much longer), so my view is that we should port this lesson to Python 3 ASAP.

If there is interest, I'm more than happy to take this on.

Thanks!

**Comment by r-gaia-cs** [comment]
> I think every beginner we teach Python 2
> puts additional load on the community
> (which has to maintain Python 2 code for that much longer),
> so my view is that we should port this lesson to Python 3 ASAP.

I agree on that.

I vote for let 5.3 still use Python2
and soon after the release of it
we change to Python3
(**remember that you will also need to change
the workshop installation instructions**).

**Comment by wking** [comment]
Previous discussion of this transition is in swcarpentry/bc#107 and
swcarpentry/workshop-template#159.

**Comment by abostroem** [comment]
There are a lot of good statistics in this blog post: I'd love to see more like this for other fields SWC teaches: http://astrofrog.github.io/blog/2015/05/09/2015-survey-results/

**Comment by vahtras** [comment]
Very interesting blog post. My main reason for not upgrading has just been to stick with default installations. Now that that the leading linux distribution Ubuntu is shifting to Python3 next year, others will likely follow and so should we.
