### ISSUE TITLE
Episode 08 - Suggestion: use double triple quotes for docstrings

### ISSUE THREAD

**Issue by niehues** [swcarpentry/python-novice-inflammation#848]
[Episode 8: Creating Functions](https://swcarpentry.github.io/python-novice-inflammation/08-func/index.html) introduces Python docstrings. I would like to suggest to replace single triple quotes (''') by double triple quotes ("""). This is the recommended way according to [PEP 8 - Style Guide](https://www.python.org/dev/peps/pep-0008/#string-quotes) and [PEP 257 - Docstring Conventions](https://www.python.org/dev/peps/pep-0257/).

Change e.g. in [episode 8](https://github.com/swcarpentry/python-novice-inflammation/blob/gh-pages/_episodes/08-func.md)

```{Python}
def offset_mean(data, target_mean_value):
    '''Return a new array containing the original data
       with its mean offset to match the desired value.

    Examples
    --------
    >>> offset_mean([1, 2, 3], 0)
    array([-1.,  0.,  1.])
    '''
    return (data - numpy.mean(data)) + target_mean_value

help(offset_mean)
```

to

```
def offset_mean(data, target_mean_value):
    """Return a new array containing the original data
       with its mean offset to match the desired value.

    Examples
    --------
    >>> offset_mean([1, 2, 3], 0)
    array([-1.,  0.,  1.])
    """
    return (data - numpy.mean(data)) + target_mean_value

help(offset_mean)
```

**Comment by ldko** [comment]
Hi @niehues ,
Thank you for the suggestion. You are right; we should use double triple quotes. Would you like to submit a Pull Request to make the changes? Thanks for submitting the issue!

**Comment by niehues** [comment]
Hello @ldko, Yes, I'll submit a Pull Request.
