### ISSUE TITLE
Importing?

### ISSUE THREAD

**Issue by abostroem** [swcarpentry/python-novice-inflammation#86]
Now that we have broken up our lessons do we plan on teaching in a single notebook or a notebook per lesson? If we are going to teach in a notebook per lesson there should be import statements at the beginning of each lesson for modules we use over and over again (such as Numpy).

**Comment by alistairwalsh** [comment]
I used a notebook per lesson, imported libraries at the start and used it as an opportunity to explain that this needs to be done as each notebook is independent.
