### ISSUE TITLE
Improving Episode 8- Functions

### ISSUE THREAD

**Issue by MDHDZ91** [swcarpentry/python-novice-inflammation#864]
In this episode the difference between return and print are discussed and when these cases are used. But nowhere is it discussed the difference between return/print when setting a variable to the function output. So variable=function(with return) creates a variable with output we can further use but variable=function(with print) creates a variable with a string. 
I know adding content to the lessons is difficult but perhaps this can be included as a note to the instructors.

**Comment by ldko** [comment]
Hi María,
Thank you for providing feedback on this lesson!

As you mention, the difference between `return` and `print` are discussed in the _Creating Functions_ episode. In particular, this is the focus of the "Return versus print" challenge. Here it gives us the function:
```
def add(a, b):
    print(a + b)
```
and the statements:
```
A = add(7, 3)
print(A)
```
and in the solution it explains:

>Python will first execute the function add with a = 7 and b = 3, and, therefore, print 10. However, because function add does not have a line that starts with return (no return “statement”), it will, by default, return nothing which, in Python world, is called None. Therefore, A will be assigned to None and the last line (print(A)) will print None. As a result, we will see:
```
Output
10
None
```
This gives us an example of a variable, `A`, being set to the result of a function that ends with a `print` call but that has no explicit `return` statement and points out that in this case the variable is set to `None`, which is the case whenever there is not an explicit `return`. 

Does this cover the point you are bringing up? If not, do you see a way to add to this challenge and/or its solution to better explain the point that needs clarifying?

**Comment by MDHDZ91** [comment]
Hi Lauren,

Thank you for your response. Yes you are correct these information covers
my suggestion.
I know this is going to sound insane but I am recovering from a concussion
and I completely missed this block of code when I was preparing for my
teaching demo. I just looked back at the lesson and everything is clearly
there.
I'm so sorry for submitting a non-issue.

My apologies,



María D. Hernández Limón
Coleman Lab  <http://biogeolabs.uchicago.edu/colemanlab/>
Graduate Student
Dept. of the Geophysical Sciences
University of Chicago
(224)-772-4017

UChicago-DAB Member
<https://voices.uchicago.edu/uchicagograd/2019/10/17/meet-the-uchicagograd-diversity-advisory-board-dab/>
| PSD EDI Student Committee Member
<https://physicalsciences.uchicago.edu/about/diversity-inclusion/committees/edi-student-committee/>
Neubauer Fellow <https://grad.uchicago.edu/fellowships/neubauer-fellows/>|DSEER
NSF Fellow <https://voices.uchicago.edu/nrtenergyandenvironment/about/>| Ford
Foundation Predoctoral Fellow
<https://sites.nationalacademies.org/PGA/FordFellowships/index.htm>

**Comment by ldko** [comment]
Hi María,
There is absolutely no need for you to apologize for submitting an issue to this repo that ends up not leading to a change. :) We appreciate the time you took to submit the issue anyway!

Thanks,
Lauren
