### ISSUE TITLE
Broken figures on github.io

### ISSUE THREAD

**Issue by chrisroat** [swcarpentry/python-novice-inflammation#880]
At the following page, the images under "Option A: Jupyter Notebook" are broken links:

https://swcarpentry.github.io/python-novice-inflammation/setup.html

I see the figures in the repo, but I am not familiar enough with gh-pages and github.io to know what went wrong.

**Comment by maxim-belkin** [comment]
Thanks for the report, Chris.
François fixed this in #881.
