### ISSUE TITLE
Overarching Narrative

### ISSUE THREAD

**Issue by mhamilt** [swcarpentry/python-novice-inflammation#887]
Mentioned in issue https://github.com/swcarpentry/python-novice-inflammation/issues/179

The lesson would really benefit from an overarching narrative, something similar to [Nelle's Pipeline in the Shell Novice](http://swcarpentry.github.io/shell-novice/01-intro/#nelles-pipeline-a-typical-problem) that gives context to each lessons. 

The inflammation data is synthetic, however integrating it within a story would avoid re-writing material and sourcing another data set.

**Comment by ldko** [comment]
This is something the maintainers have talked about doing and are in support of. @annefou was planning to updated episode 1 with examples more relevant to the inflammation story. Have you had a chance to work on that, Anne?
