### ISSUE TITLE
Data file is in data subdirectory, numpy.loadtxt fails

### ISSUE THREAD

**Issue by janetriley** [swcarpentry/python-novice-inflammation#9]
At [line 39 of 01-numpy.md](https://github.com/swcarpentry/python-novice-inflammation/blame/gh-pages/01-numpy.md#L39) , we load our first data file:

`numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')`

The .csv file is in the data directory.  Since I was working from the top level directory, the file wasn't found. I had to change it to:
 
`numpy.loadtxt(fname='data\inflammation-01.csv', delimiter=',')`

Are students expected to work from the data directory? 

See also the discussion on  issue  #4 .

**Comment by gvwilson** [comment]
You're right, they should load from the sub-directory.
- G

**Comment by janetriley** [comment]
Thanks. I'll put together a PR in the next couple evenings, and I'll keep an eye out for it in the rest of the tutorial.

**Comment by r-gaia-cs** [comment]
@janetriley Can you send a pull request with https://github.com/janetriley/python-novice-inflammation/commit/f0e7728ad9a12c0b1bcf4c84c950985808edcdcb? If you prefer we can do that for you.

**Comment by wking** [comment]
On Wed, Apr 08, 2015 at 04:59:43AM -0700, Raniere Silva wrote:
> @janetriley Can you send a pull request with
> https://github.com/janetriley/python-novice-inflammation/commit/f0e7728ad9a12c0b1bcf4c84c950985808edcdcb?
> If you prefer we can do that for you.

It looks like there are forward slashes in that commit, but the
original post here claims a backslash (presumably for Windows).
Personally, I'd use os.path.join(…) to get the path, but I'm ok
hard-coding the forward slash if we know it will also work on Windows.

**Comment by janetriley** [comment]
@r-gaia-cs, there were several conflicts from unrelated changes.  It will take less time to do it off a fresh copy of gh-pages.

**Comment by janetriley** [comment]
@wking - hadn't thought about Windows, and don't have a Windows environment to test with.  Good catch.

This will mean changing the lesson in 1_numpy.html . Can we work out a draft here before I implement it?  I'm navigating between providing enough explanation so it's not magic, yet not getting sidetracked into a big mini-lesson about operating system compatibility and file separators.

Here's the current text,  minus some formatting:

---

In order to load our inflammation data, we need to import a library called NumPy. In general you should use this library if you want to do fancy things with numbers, especially if you have matrices. We can load NumPy using:


`import numpy`

Importing a library is like getting a piece of lab equipment out of a storage locker and setting it up on the bench. Once it's done, we can ask the library to read our data file for us:

`numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')`

---



In the revised version, the first part will stay the same:

---
In order to load our inflammation data, we need to import a library called NumPy. In general you should use this library if you want to do fancy things with numbers, especially if you have matrices. We can load NumPy using:

`import numpy`

Importing a library is like getting a piece of lab equipment out of a storage locker and setting it up on the bench. 
```

Add something like this:

```
Next, we'll read in our data file.  All of our data files are located in the data subdirectory. Windows, Mac OSX, and UNIX use different conventions to write the path to a file. To ensure our code works on all operating systems, we use a helper from the os library.

`import os`

We describe where to find our inflammation data:

`file_path = os.path.join('data', 'inflammation-01.csv')`

Now we can ask the library to read our data file for us:

`numpy.loadtxt(fname=file_path, delimiter=',')`

---

In subsequent uses I'll inline the os.path.join.  I'm breaking it into two steps here because doing multiple function calls is confusing the first time one sees it. 

Thoughts?
Janet

**Comment by wking** [comment]
On Tue, Apr 14, 2015 at 09:46:16AM -0700, Janet Riley wrote:
> Next, we'll read in our data file.  All of our data files are
> located in the data subdirectory. Windows, Mac OSX, and UNIX use
> different conventions to write the path to a file. To ensure our
> code works on all operating systems, we use a helper from the os
> library.

I think our convention is “Unix” not “UNIX”:

  $ git grep Unix origin/gh-pages | wc -l
  8
  $ git grep UNIX origin/gh-pages | wc -l
  0

Which matches Wikipedia when not referring to the trademarked term
[1].

And since Apple finally dropped their OS 9 colon separators (maybe in
2002 [2]?), for major systems it's just Windows (backslash)
vs. everyone else (forward slash).

> We describe where to find our inflammation data:
> 
> `file_path = os.path.join('data', 'inflammation-01.csv')`
> 
> Now we can ask the library to read our data file for us:
> 
> `numpy.loadtxt(fname=file_path, delimiter=',')`

This seems reasonable to me, but:

1. At the 2015-04-09-UW workshops we just had folks launch
   Jupyter/IPython from the data directory, so there was no need to
   reach into subdirectories right off the bat.  This was how I read
   @gvwilson's suggestion [3].
2. Folks who went through our POSIX-shell lesson may be confused with
   the patter, because Bash has been showing them forward slashes on
   Windows.

[1]: http://en.wikipedia.org/wiki/Unix#Branding
[2]: http://www.dslreports.com/forum/r25090372-The-death-of-the-colon-file-path-separator
[3]: https://github.com/swcarpentry/python-novice-inflammation/issues/9#issuecomment-70907851

**Comment by janetriley** [comment]
Given @wking's comment:
*At the 2015-04-09-UW workshops we just had folks launch
   Jupyter/IPython from the data directory, so there was no need to
   reach into subdirectories right off the bat.  This was how I read
   @gvwilson's suggestion*

and @gvwilson's comment,
*You're right, they should load from the sub-directory.*

this ticket is a non-issue.  The workshop practice is to start from the data directory.

I'm closing this ticket.  It can be reopened if the practice changes.
