### ISSUE TITLE
Episode 8 Creating Functions - About variable scope

### ISSUE THREAD

**Issue by chavid** [swcarpentry/python-novice-inflammation#934]
<details>
<summary><strong>Unexplained key point about reading an outside variable</strong></summary>

The final list of key points include : "If a variable is not defined within the function it is used, Python looks for a definition before the function call".

I am afraid a Python beginner will not understand such a statement, given what was detailed (or not detailed) in the episode, and I find that this information comes late.

Key points are a kind of summary of what was explained during the episode. Am I wrong ?

I strongly support the presence of the exercise called "Variables Inside and Outside Functions", because most python beginners will notice that reading an outside variable works, and wrongly infer that they can also simply modify it from within the function. Yet, showing the modification failure, and not the successful reading of an outside variable, seem to me incomplete, half-way. The final added key point does not really cover the point.

I would review "Variables Inside and Outside Functions" exercise, so to show both the successfull reading of an outside variable, and the failed writing of it. If the lesson is already too long, whatsoever, I would remove the final key point, which comes too late if the concept is not explained before. Don' you think so ?
</details>

**Comment by ldko** [comment]
Thanks for highlighting this @chavid.

Yes, as you say, the key points are meant to outline the concepts introduced in the episode. I think modifying the exercise to make the point of reading an outside variable would be ok to justify the key point's presence. Alternatively, it might be worth extending the variable scope section of the episode to include an example/explanation about this.  Would you like to submit a pull request?

**Comment by chavid** [comment]
Ok. If you think it is ok for the time budget, I think it is really worth to say a word about it in the "variable scope" section. The subsequent question being : to be complete, do we say a word about the keyword "global" ? For the time being, I will make the hypothesis the answer is "no". It is not that bad to let the beginner think he cannot change a global variable, which is a very bad practice most of the cases.

**Comment by maxim-belkin** [comment]
> The subsequent question being : to be complete, do we say a word about the keyword "global" ? For the time being, I will make the hypothesis the answer is "no".

Yes, let's not mention `global` at the moment.

**Comment by ldko** [comment]
This was closed by #942. Thank you @chavid !
