### ISSUE TITLE
How to Contribute to an Open Source Project on GitHub in Contribution Guidelines needs update

### ISSUE THREAD

**Issue by leriomaggio** [swcarpentry/python-novice-inflammation#944]
While looking at the instructions on how to do my first contribution to the Software Carpentries material, I noticed that the link to the `How to Contribute to an Open Source Project on GitHub` is outdated. 

In particular, the link reported in the guidelines is [this](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github), whereas the new updated one should be this:[new link](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github)

A PR to fix this issue is coming in a few minutes :)

HTH

**Comment by leriomaggio** [comment]
In the meantime, I've checked all other links in the page and they do all work.

**Comment by ldko** [comment]
This was closed by #945. Thank you @leriomaggio !
