### ISSUE TITLE
Code provided for students contain python code not compatible with python 3

### ISSUE THREAD

**Issue by dpshelio** [swcarpentry/python-novice-inflammation#948]
At least one file in the `code` directory, e.g., `gen_inflammation.py` fails when running it with python 3. The [problem is the "division" not giving an integer](https://github.com/swcarpentry/python-novice-inflammation/blob/11643f14d31726f2f60873c4ca1230fff0bbf108/code/gen_inflammation.py#L19). It needs to be changed to
```diff
- upper / 4
+ upper // 4
```

This was spotted by a student trying to check their installation and running different files.
Other files may have similar errors. I'd suggest running and testing via CI everything we provide to the students.

**Comment by ldko** [comment]
Thanks for reporting the integer division problem @dpshelio . It has been fixed in #946. If you notice other errors in the code, we welcome you to report them in new issues, or if you would like to open a PR to set up testing of all of the code via CI, we can take a look. Thanks again!
