### ISSUE TITLE
Suggestion to avoid confusion in episode 2 Analyzing Patient Data

### ISSUE THREAD

**Issue by pwgroen** [swcarpentry/python-novice-inflammation#997]
In https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html it says:
"This dotted notation is used everywhere in Python: the thing that appears before the dot contains the thing that appears after."

It could be confusing at first reading (before continuing with "As an example"), because it could at that point refer to the dots in the numpy.loadtxt output (i.e. in array([[ 0.,  0.,  1., ...,  3 etc.) or the dots in "numpy.loadtxt(...) is a function call".

So, the suggestion is to be more explicit, e.g. "This dotted notation (i.e. the dot in numpy.loadtext) is used everywhere (...)".

**Comment by ozieblo-repository** [comment]
https://github.com/swcarpentry/python-novice-inflammation/pull/1014

Please review the resolution of the above issue.

**Comment by noatgnu** [comment]
Hi, I have reviewed the resolution and merged it with the code base. Thank you for your contribution.
