### ISSUE TITLE
Suggestion to change listname (or list element of) primes in episode 4 Storing Multiple Values in Lists

### ISSUE THREAD

**Issue by pwgroen** [swcarpentry/python-novice-inflammation#998]
In https://swcarpentry.github.io/python-novice-inflammation/04-lists/index.html under Heterogeneous Lists, the list [1, 3, 5, 7, 2] is called "primes", while 1 is not a prime number.
A suggestion could be that the name of the list is changed, or that 1 is popped from it.

**Comment by indiauppal** [comment]
The easiest way is probably taking 1 out of the list and having odds = [3, 5, 7].
I'll submit a pull request.

**Comment by pwgroen** [comment]
Thank you.

**Comment by noatgnu** [comment]
Thank you for submitting the needed pull request to fix the document. I have merged the pr.
